//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingOrderLines_StampingPlates
    {
        public long ID { get; set; }
        public byte[] Timestamp { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long IncomingOrderLinesID { get; set; }
        public int BrandID { get; set; }
        public int ShapeID { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public int Quantity { get; set; }
        public bool WasGift { get; set; }
        public string Description { get; set; }
        public Nullable<long> StampingPlateID { get; set; }
        public bool Converted { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual IncomingOrderLine IncomingOrderLine { get; set; }
    }
}
