//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingOrderLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomingOrderLine()
        {
            this.IncomingOrderLines_Polishes = new HashSet<IncomingOrderLines_Polishes>();
        }
    
        public long ID { get; set; }
        public byte[] Timestamp { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long IncomingOrderID { get; set; }
        public long IncomingLineTypeID { get; set; }
        public decimal Price { get; set; }
        public int Qty { get; set; }
        public string Notes { get; set; }
        public string Tracking { get; set; }
        public Nullable<int> ShippingProviderID { get; set; }
        public string Name { get; set; }
    
        public virtual IncomingLineType IncomingLineType { get; set; }
        public virtual IncomingOrder IncomingOrder { get; set; }
        public virtual ShippingProvider ShippingProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingOrderLines_Polishes> IncomingOrderLines_Polishes { get; set; }
    }
}
