//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;

    public partial class Log
    {
        public long ID { get; set; }
        public string LogType { get; set; }
        public string Details { get; set; }
        public string FriendlyMessage { get; set; }
        public string Error { get; set; }
        public string StackTrace { get; set; }
        public string InputData { get; set; }
        public string OutputData { get; set; }
        public Nullable<long> ParentLogID { get; set; }
    }
}
