//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polishes_ARCHIVE
    {
        public long ID { get; set; }
        public int ColorID { get; set; }
        public int BrandID { get; set; }
        public byte[] Timestamp { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public string Name { get; set; }
        public int ColorNumber { get; set; }
        public string Label { get; set; }
        public int Coats { get; set; }
        public int Quantity { get; set; }
        public bool HasBeenTried { get; set; }
        public bool WasGift { get; set; }
    }
}
