//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolishWarehouseEntities : DbContext
    {
        public PolishWarehouseEntities()
            : base("name=PolishWarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Polish> Polishes { get; set; }
        public virtual DbSet<Polishes_PolishTypes> Polishes_PolishTypes { get; set; }
        public virtual DbSet<PolishType> PolishTypes { get; set; }
        public virtual DbSet<Polishes_AdditionalInfo> Polishes_AdditionalInfo { get; set; }
        public virtual DbSet<Polishes_Glitter_Colors> Polishes_Glitter_Colors { get; set; }
        public virtual DbSet<Polishes_Secondary_Colors> Polishes_Secondary_Colors { get; set; }
    }
}
