//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolishWarehouseEntities : DbContext
    {
        public PolishWarehouseEntities()
            : base("name=PolishWarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Polish> Polishes { get; set; }
        public virtual DbSet<Polishes_PolishTypes> Polishes_PolishTypes { get; set; }
        public virtual DbSet<PolishType> PolishTypes { get; set; }
        public virtual DbSet<Polishes_Glitter_Colors> Polishes_Glitter_Colors { get; set; }
        public virtual DbSet<Polishes_Secondary_Colors> Polishes_Secondary_Colors { get; set; }
        public virtual DbSet<BrandCategory> BrandCategories { get; set; }
        public virtual DbSet<Polishes_DestashInfo> Polishes_DestashInfo { get; set; }
        public virtual DbSet<Polishes_AdditionalInfo> Polishes_AdditionalInfo { get; set; }
        public virtual DbSet<Polishes_Images> Polishes_Images { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<IncomingLineType> IncomingLineTypes { get; set; }
        public virtual DbSet<IncomingOrderLine> IncomingOrderLines { get; set; }
        public virtual DbSet<IncomingOrder> IncomingOrders { get; set; }
        public virtual DbSet<ShippingProvider> ShippingProviders { get; set; }
        public virtual DbSet<Polishes_AdditionalInfo_ARCHIVE> Polishes_AdditionalInfo_ARCHIVE { get; set; }
        public virtual DbSet<Polishes_ARCHIVE> Polishes_ARCHIVE { get; set; }
        public virtual DbSet<Polishes_Glitter_Colors_ARCHIVE> Polishes_Glitter_Colors_ARCHIVE { get; set; }
        public virtual DbSet<Polishes_Images_ARCHIVE> Polishes_Images_ARCHIVE { get; set; }
        public virtual DbSet<Polishes_PolishTypes_ARCHIVE> Polishes_PolishTypes_ARCHIVE { get; set; }
        public virtual DbSet<Polishes_Secondary_Colors_ARCHIVE> Polishes_Secondary_Colors_ARCHIVE { get; set; }
        public virtual DbSet<Polishes_DestashInfo_ARCHIVE> Polishes_DestashInfo_ARCHIVE { get; set; }
        public virtual DbSet<IncomingOrderLines_Polishes> IncomingOrderLines_Polishes { get; set; }
        public virtual DbSet<IncomingOrderLines_StampingPlates> IncomingOrderLines_StampingPlates { get; set; }
        public virtual DbSet<StampingPlateDesign> StampingPlateDesigns { get; set; }
        public virtual DbSet<StampingPlate> StampingPlates { get; set; }
        public virtual DbSet<StampingPlates_AdditionalInfo> StampingPlates_AdditionalInfo { get; set; }
        public virtual DbSet<StampingPlates_AdditionalInfo_ARCHIVE> StampingPlates_AdditionalInfo_ARCHIVE { get; set; }
        public virtual DbSet<StampingPlates_ARCHIVE> StampingPlates_ARCHIVE { get; set; }
        public virtual DbSet<StampingPlates_DestashInfo> StampingPlates_DestashInfo { get; set; }
        public virtual DbSet<StampingPlates_DestashInfo_ARCHIVE> StampingPlates_DestashInfo_ARCHIVE { get; set; }
        public virtual DbSet<StampingPlates_Images> StampingPlates_Images { get; set; }
        public virtual DbSet<StampingPlates_Images_ARCHIVE> StampingPlates_Images_ARCHIVE { get; set; }
        public virtual DbSet<StampingPlates_StampingPlateDesigns> StampingPlates_StampingPlateDesigns { get; set; }
        public virtual DbSet<StampingPlates_StampingPlateThemes> StampingPlates_StampingPlateThemes { get; set; }
        public virtual DbSet<StampingPlateShape> StampingPlateShapes { get; set; }
        public virtual DbSet<StampingPlateTheme> StampingPlateThemes { get; set; }
    }
}
