//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polish()
        {
            this.Polishes_PolishTypes = new HashSet<Polishes_PolishTypes>();
            this.Polishes_Glitter_Colors = new HashSet<Polishes_Glitter_Colors>();
            this.Polishes_Secondary_Colors = new HashSet<Polishes_Secondary_Colors>();
        }
    
        public long ID { get; set; }
        public int ColorID { get; set; }
        public int BrandID { get; set; }
        public byte[] Timestamp { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public bool HasBeenTried { get; set; }
        public bool WasGift { get; set; }
        public int ColorNumber { get; set; }
        public int Coats { get; set; }
        public int Quantity { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        public virtual Polishes_AdditionalInfo Polishes_AdditionalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polishes_PolishTypes> Polishes_PolishTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polishes_Glitter_Colors> Polishes_Glitter_Colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polishes_Secondary_Colors> Polishes_Secondary_Colors { get; set; }
        public virtual Polishes_DestashInfo Polishes_DestashInfo { get; set; }
    }
}
