//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{

    public partial class Polishes_Glitter_Colors
    {
        public long ID { get; set; }
        public long PolishID { get; set; }
        public int ColorID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Polish Polish { get; set; }
    }
}
