//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polishes_AdditionalInfo
    {
        public long PolishID { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string GiftFromName { get; set; }
    
        public virtual Polish Polish { get; set; }
    }
}
