//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{

    public partial class Setting
    {
        public long ID { get; set; }
        public string KeyName { get; set; }
        public string KeyValue { get; set; }
        public string KeyDataType { get; set; }
        public bool PublicSetting { get; set; }
    }
}
