//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StampingPlates_DestashInfo
    {
        public long StampingPlateID { get; set; }
        public int Qty { get; set; }
        public string BuyerName { get; set; }
        public Nullable<decimal> AskingPrice { get; set; }
        public Nullable<decimal> SoldPrice { get; set; }
        public string TrackingNumber { get; set; }
        public string Notes { get; set; }
        public string InternalNotes { get; set; }
        public string SaleStatus { get; set; }
    
        public virtual StampingPlate StampingPlate { get; set; }
    }
}
