//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StampingPlate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StampingPlate()
        {
            this.StampingPlates_Images = new HashSet<StampingPlates_Images>();
            this.StampingPlates_StampingPlateDesigns = new HashSet<StampingPlates_StampingPlateDesigns>();
            this.StampingPlates_StampingPlateThemes = new HashSet<StampingPlates_StampingPlateThemes>();
        }
    
        public long ID { get; set; }
        public int BrandID { get; set; }
        public int ShapeID { get; set; }
        public byte[] Timestamp { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public int Quantity { get; set; }
        public bool WasGift { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual StampingPlates_AdditionalInfo StampingPlates_AdditionalInfo { get; set; }
        public virtual StampingPlates_DestashInfo StampingPlates_DestashInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StampingPlates_Images> StampingPlates_Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StampingPlates_StampingPlateDesigns> StampingPlates_StampingPlateDesigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StampingPlates_StampingPlateThemes> StampingPlates_StampingPlateThemes { get; set; }
        public virtual StampingPlateShape StampingPlateShape { get; set; }
    }
}
