//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StampingPlates_StampingPlateThemes
    {
        public long ID { get; set; }
        public long StampingPlateID { get; set; }
        public int ThemeID { get; set; }
    
        public virtual StampingPlate StampingPlate { get; set; }
        public virtual StampingPlateTheme StampingPlateTheme { get; set; }
    }
}
