//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishWarehouseData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StampingPlates_ARCHIVE
    {
        public long ID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> WasGift { get; set; }
    }
}
